name: Kuskua
favicon: null
layout_spectrum: 0.2706340942531824
typography_spectrum: 0.611816544784233
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12426447286270559
  lightness: 0.4376460942439735
  saturation: 0.6352331496309489
  rhythmicContrast: 0.19809233746491373
purpose: []
